const ID_ROUTE_PARAM = ':id';

const ROUTE_USERS = '/users';

export const ROUTE_NAME_USERS_LIST_PAGE = 'USER_LIST_PAGE';
export const ROUTE_URL_USERS_LIST_PAGE = ROUTE_USERS;
export const ROUTE_URL_USER_PAGE = `${ROUTE_USERS}${ID_ROUTE_PARAM}`;
export const ROUTE_NAME_USER_PAGE = `USER_CARD_PAGE`;
